### ISSUE TITLE
Nothing happen when I try to make somes customizations

### ISSUE THREAD

**Issue by methys** [Microsoft/PowerBI-visuals-StrippetsBrowser#59]
Hi,
I tried to modify the capbilities.json file in order to change the display name of the Source Image attribut

Before 
    {
      "name": "sourceImage",
      "displayName": "Source Image (url)",
      "description": "URL for an image to display in the top-right corner of the thumbnail",
      "kind": 0
    },

After 
    {
      "name": "sourceImage",
      "displayName": "Source Image (url) TEST",
      "description": "URL for an image to display in the top-right corner of the thumbnail",
      "kind": 0
    },

>> I run npm run package, all thing works fine but when I import the "essex.widget.strippetbrowser.pbiviz" file into powerbi, nothing changed ...

I also tried to modify css file to modify the card-icon sizing, same problem, nothing changes..

Is there anything else to do ?

**Comment by psmacmur** [comment]
PowerBI will, by default, load the official build of the visual, if yours has the same GUID.  There are two workarounds, one is to use query parameter flags to instruct PowerBI to let your custom build through.  In the browser, add this to the end of your URL: `?sandboxVisualsEnabled=false&approvedResourcesDisabled=true&unmin=true`

**Comment by methys** [comment]
the first solution (Using url '?sandboxVisualsEnabled=false&approvedResourcesDisabled=true&unmin=true' ) worked fine , but i want to implement the solution using query parameters flag ,this did not work please take a look to the screenshot.
![tt](https://user-images.githubusercontent.com/11379621/27736345-b83737a6-5d9b-11e7-8f41-12a5cf97260c.jpg)

**Comment by psmacmur** [comment]
It looks like you're trying to use your custom build in PowerBI Desktop.
Query Parameters in PBI are completely unrelated to the browser address bar
query parameters, so they will not help with this issue.  Nice try,
though.  Alas, if you want to use your custom build in PBI Desktop, you
will have to give your visual a custom GUID in pbivis.json.

Peter

**Comment by methys** [comment]
Hi Peter,
It worked like a charm !!
Thank you.
